#!/usr/bin/python

import sys
import re


def main():
    remove_escape_seq = False
    if 'ascii' in sys.argv:
        remove_escape_seq = True
        sys.argv.remove('ascii')

    trimming_pos = 33
    if len(sys.argv) > 1:
        trimming_pos = int(sys.argv[1])

    filtered = apply_filter(sys.stdin, trimming_pos, remove_escape_seq)

    for line in filtered:
        print(line, end='')


def apply_filter(infile, trimming_pos, remove_escape_seq):
    remove_escape_seq_re = re.compile(r"\[[0-9;]*[a-zA-Z]")
    for line in infile:
        if remove_escape_seq:
            line = remove_escape_seq_re.sub('', line)
        yield line[trimming_pos:]


if __name__ == '__main__':
    main()

# vim: ft=python
